# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import compiler_pb2 as compiler__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compiler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompilerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLanguageSpec = channel.unary_unary(
                '/glykon.compiler.CompilerService/GetLanguageSpec',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=compiler__pb2.LanguageSpecReply.FromString,
                _registered_method=True)
        self.PredictNext = channel.unary_unary(
                '/glykon.compiler.CompilerService/PredictNext',
                request_serializer=compiler__pb2.PredictRequest.SerializeToString,
                response_deserializer=compiler__pb2.PredictReply.FromString,
                _registered_method=True)
        self.GetSemanticHints = channel.unary_unary(
                '/glykon.compiler.CompilerService/GetSemanticHints',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=compiler__pb2.SemanticHintsReply.FromString,
                _registered_method=True)
        self.ParseOk = channel.unary_unary(
                '/glykon.compiler.CompilerService/ParseOk',
                request_serializer=compiler__pb2.PredictRequest.SerializeToString,
                response_deserializer=compiler__pb2.ParseOkReply.FromString,
                _registered_method=True)


class CompilerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLanguageSpec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSemanticHints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseOk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompilerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLanguageSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLanguageSpec,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=compiler__pb2.LanguageSpecReply.SerializeToString,
            ),
            'PredictNext': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictNext,
                    request_deserializer=compiler__pb2.PredictRequest.FromString,
                    response_serializer=compiler__pb2.PredictReply.SerializeToString,
            ),
            'GetSemanticHints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSemanticHints,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=compiler__pb2.SemanticHintsReply.SerializeToString,
            ),
            'ParseOk': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseOk,
                    request_deserializer=compiler__pb2.PredictRequest.FromString,
                    response_serializer=compiler__pb2.ParseOkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glykon.compiler.CompilerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glykon.compiler.CompilerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompilerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLanguageSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glykon.compiler.CompilerService/GetLanguageSpec',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            compiler__pb2.LanguageSpecReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glykon.compiler.CompilerService/PredictNext',
            compiler__pb2.PredictRequest.SerializeToString,
            compiler__pb2.PredictReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSemanticHints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glykon.compiler.CompilerService/GetSemanticHints',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            compiler__pb2.SemanticHintsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseOk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glykon.compiler.CompilerService/ParseOk',
            compiler__pb2.PredictRequest.SerializeToString,
            compiler__pb2.ParseOkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
